---

networks:
  rustdesk-net:
    external: false

services:
  hbbs:
    container_name: hbbs
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      #- 21118:21118
    image: rustdesk/rustdesk-server:${RUSTDESK_SERVER_VERSION}
    build:
      context: .
    command: hbbs
    #command: hbbs -r rustdesk.misaka.net:21117
    volumes:
      - ./data:/root
    networks:
      - rustdesk-net
    depends_on:
      - hbbr
    restart: unless-stopped
    extra_hosts:
      - "rustdesk.misaka.net:192.168.50.250"

  hbbr:
    container_name: hbbr
    ports:
      - 21117:21117
      #- 21119:21119
    image: rustdesk/rustdesk-server:${RUSTDESK_SERVER_VERSION}
    build:
      context: .
    command: hbbr
    volumes:
      - ./data:/root
    networks:
      - rustdesk-net
    restart: unless-stopped
    extra_hosts:
      - "rustdesk.misaka.net:192.168.50.250"

